# Generated by Django 6.0.4 on 2026-04-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.AddField(
            model_name='category',
            name='main_categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blogs.maincategory'),
        ),
    ]
