# Generated by Django 6.0.4 on 2026-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_created_at_blogpost_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
