# Generated by Django 6.0.4 on 2026-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
