# Generated by Django 6.0.4 on 2026-07-08 08:44

from django.db import migrations, models


def copy_main_category_to_main_categories(apps, schema_editor):
    BlogPost = apps.get_model('blogs', 'BlogPost')
    for post in BlogPost.objects.all():
        if post.main_category_id:
            post.main_categories.add(post.main_category_id)

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogpost_author_blogpost_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='main_categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blogs.maincategory'),
        ),
        migrations.RunPython(copy_main_category_to_main_categories),
    ]
