# Generated by Django 6.0.4 on 2026-07-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blogpost_main_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='main_category',
        ),
    ]
